### PR TITLE
Latest objects

### PR DESCRIPTION
**Pull request by RaresAmbrus**
Support for getting only the latest dynamic objects (between a new observation and the previous one).

### CODE REVIEW

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
still DDoS issues on github...

**Comment by marc-hanheide** [comment]
now, that's a proper bug: `Could not find simple_xml_parser in keys.`

**Comment by marc-hanheide** [comment]
What is `simple_xml_parser` and where should it be?

**Comment by RaresAmbrus** [comment]
Yes, wrong package name. Was just fixing it.

**Comment by RaresAmbrus** [comment]
Seems to be fixed now. Merging this.

**Pull request merged**
