### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by RaresAmbrus**
This PR adds the following new nodes:
- strands_sweep_registration : @jekekrantz's feature based registration using the ceres optimizer for registering sweeps
- calibrate_sweeps : takes a number of sweeps and uses feature registration to correct and rebuild the clouds
- object_manager : a node that publishes through services the detected dynamic objects
- semantic_map_publisher : a node that publishes the latest sweep (as point cloud or octomap) at a waypoint

Also, a number of improvements to existing nodes:
- using the feature registration (if available) to register sweeps internally
- saving/loading of registration features
- saving/loading of calibrated sweep camera poses
- additions to the xml parsers
- lots of bugfixes

### CODE REVIEW

**Comment by marc-hanheide** [comment]
I just enabled devel builds for this repository. Expect jenkins complaining...

**Comment by marc-hanheide** [comment]
and we have the first culprit: `Could not find opencv2 in keys.`

**Comment by RaresAmbrus** [comment]
I think this one's from @jekekrantz's repo. I'll look into it.

**Comment by RaresAmbrus** [comment]
There are a couple of include issues, however the bigger problem is that @jekekrantz is using some opencv nonfree features (SURF)  which aren't part of opencv anymore. We'll have to either find some workaround or remove that part of the code.

**Comment by marc-hanheide** [comment]
ouch! So SURF isn't included in the ubuntu packages? Or is it just a matter of including the right license text?

**Comment by RaresAmbrus** [comment]
I think it used to be a part of the standard opencv package but it's not anymore. But @jekekrantz can correct me.

**Comment by hawesie** [comment]
http://stackoverflow.com/a/27493595

?

**Comment by marc-hanheide** [comment]
Ah, not nice... including another ppa renders the easy install we had a bit void. We could replicate the ppa in our own server, but it's not exactly nice... not entirely sure if it would be better to include the SURF code in the own project?

**Comment by RaresAmbrus** [comment]
For now we removed the nonfree opencv stuff. It might make sense to look into a way to include it in our projects in the future, as other people might want to use it as well. 
Also, since SURF/SIFT/other things are now specifically included in the nonfree part of opencv, I don't know if we can just copy that code and redistribute it in our packages. We would have to adjust our licenses I guess.

**Pull request merged**
