### PR TITLE
Adding registration methods

### PR DESCRIPTION
**Pull request by RaresAmbrus**
Major additions:
- siftgpu package (used heavily for the optimization) - needs CUDA.
- observation_registration_services - package with service definitions for the observation registration and additional view registration
- observation_registration_server - registers two observations (sweeps)
- additional_view_registration_server - registers additional views. Can also register the views to a sweep.
- some bugfixes. 

Documentation to come soon.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
One comment: wasn't siftgpu already included in [V4R](https://github.com/strands-project/V4R). Maybe @ToMadoRe knows. 
Then, I think you define somewhere in there what CUDA version is needed, don't you?

**Comment by RaresAmbrus** [comment]
@marc-hanheide yes, in v4r it's checked out from source as an external project: https://github.com/strands-project/v4r/blob/master/3rdparty/SiftGPU/CMakeLists.txt 
The one I want to include is basically a catkinized version of that, forked from a different repository. In the siftgpu CMakeLists.txt, the required version of CUDA is already specified : https://github.com/RaresAmbrus/strands_3d_mapping/blob/hydro-devel/observation_registration/siftgpu/CMakeLists.txt#L9
I'm not sure what else to add to allow jenkins to find a newer version.

**Comment by marc-hanheide** [comment]
The question is, does it really need that CUDA version as obviously it's not the official one in Ubuntu 14.04. Would it work also with a lower version?

**Comment by RaresAmbrus** [comment]
Hmm good question. I'll try to set up CUDA 5.5 on my machine and see if it still works.

**Comment by marc-hanheide** [comment]
For proper testing, you should uninstall any newer CUDA and only install the Ubuntu Version.

**Comment by RaresAmbrus** [comment]
@marc-hanheide thanks, lowering the CUDA version fixed the issue.

**Pull request merged**
