### PR TITLE
New package, for now just for running octomap with the nav stack

### PR DESCRIPTION
**Pull request by nilsbore**
Transferred stuff from 3d_mapping, added args for resolution of octomap and map_server map file. Changed to move the scitos_2d_navigation package for localization. Would be really nice if someone with a robot could test this. You need to start the state_publisher before running this. Run by roslaunch octomap_launch octomap.launch map:=(PATH_TO_MAP)/map.yaml.

### CODE REVIEW

**Comment by bfalacerda** [comment]
works on bob

**Comment by kunzel** [comment]
@BFALacerda Does this mean that you could adjust the PTU and make a proper OctoMap then?

**Comment by bfalacerda** [comment]
Nop, just octomapped the floor...

**Pull request merged**
