### PR TITLE
Added cxx_flag -mno-avx

### PR DESCRIPTION
**Pull request by ToMadoRe**
to tackle assembler errors during compiling on some new Intel core processors

### CODE REVIEW

**Comment by hawesie** [comment]
These commits don't actually add `-mno-avx` anywhere.

**Comment by cdondrup** [comment]
See: https://github.com/strands-project/scitos_3d_mapping/issues/30#issuecomment-48592906
I think that should work

**Comment by ToMadoRe** [comment]
no, but you can compile the whole workspace with just one additional (global) argument `catkin_make -DCMAKE_CXX_FLAGS=-mno-avx`. Otherwise you would have to change all CMakelists.txt files in the strands workspace to include this additional `-mno-avx` argument. As I don't know if this is always desired (e.g. when compiling on older machines), I think this is the better solution.

**Comment by cdondrup** [comment]
If we want to make our code publicly available we should get rid of as many command line arguments to cmake as possible imho.

**Comment by ToMadoRe** [comment]
But what if not everyone wants to compile without AVX optimization(e.g. someone using a new gcc)? Everyone could still decide what flags he wants to have for compiling our code on their machine. So, I think we should at least just add the flags instead of overwriting them as it is done in some packages right now. Adding `-mno-avx` by default or not is probably more a matter of taste.

**Comment by mudrole1** [comment]
This is issue of more packages, as I listed in issue #30 It seems to me that this needs broader discussion. Just to remind, that if we will prefer the solution with flag, we should add this to installation wiki:
https://github.com/strands-project/strands_systems/wiki/Hydro-Installation-Instructions

**Comment by cdondrup** [comment]
This PR actually just adds `${CMAKE_CXX_FLAGS}` to the `set(CMAKE_CXX_FLAGS "... ${CMAKE_CXX_FLAGS}")` commands and is therefore harmless. I will merge this for now as it allows to set the cmake flags by hand if needed. The discussion if setting flags on the commandline is the correct solution to this can be continued in #30

**Pull request merged**
