### PR TITLE
Metric map <-> mongodb integration

### PR DESCRIPTION
**Pull request by RaresAmbrus**
- Added support for logging room sweeps into mongodb
- Importing room observations from the databse and saving them to disk
- Bugfixes

### CODE REVIEW

**Comment by marc-hanheide** [comment]
This looks good at a first glance. However, a few quick question:
1. How is this different to the sweep and store stuff that @Jailander and @gestom have been using? Maybe they can comment?
2. Can you please provide a README, covering the following:
   1. What exactly is the launch file people need to include for the marathon?
   2. Is there an action server interface that people can use to schedule the scan action?

**Comment by marc-hanheide** [comment]
Also, one other question: Why XML? JSON would be natively supported by mongodb, and easily understood by python, as would be YAML. Using XML seems a bit annoying here. Or did I read the code wrong?

**Comment by RaresAmbrus** [comment]
@marc-hanheide we have been using metric maps for a while now, and this PR allows metric map data originating from a PTU sweep to be stored in the mongodb database in addition to or instead of  storing it on the disk. For each sweep I save the following data: date & time, patrol run number and room number (this field has been superseded by the waypoint id field, still, it allows recording data without the topological localization), waypoint id, centroid, a vector of transforms corresponding to each position where the PTU stops, a vector of point clouds acquired at each position,a vector of intrinsic camera parameters for the images used to generate the point clouds. The point clouds are obtained as a result of averaging a number of depth and rgb images at each position, and I am thinking about recording each individual image as well (would be useful in case I want to remove moving object from the scene later), though that would obviously increase the size of each observation. 

The action server and launch files are the same we used at G4S and during the review; I'll double check that everything is in order tomorrow.

Regarding the choice of XML, I have been capturing and storing this data before we started using mongodb, and I keep track of it through xml files saved on the disk, with each sweep data accompanied by an xml file. In addition I am more familiar with xml than I am with either yaml or json. With this PR I have also provided an executable that reads stored metric map data  along with corresponding xml files from mongodb and saves it to the disk, for further processing; this is what we would use to extract saved data from the database. 

I am not sure what @Jailander or @gestom are recording, but I think the underlying idea is different as is the data being recorded. However, I think the action servers used for the sweeps are quite similar, but the sweep action server as such is not part of this repository.

**Comment by Jailander** [comment]
yes this is different since we are storing topics at each PTU position we are not doing any postprocessing

**Comment by marc-hanheide** [comment]
Cool. Thanks a lot. Still learning...

**Pull request merged**
